// This file will be generated by Supabase CLI
// Run: npm run type:generate after setting up Supabase project

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      api_keys: {
        Row: {
          id: string
          user_id: string
          name: string
          key_hash: string
          created_at: string
          last_used: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          key_hash: string
          created_at?: string
          last_used?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          key_hash?: string
          created_at?: string
          last_used?: string | null
          is_active?: boolean
        }
      }
      credit_balance: {
        Row: {
          user_id: string
          balance: number
          updated_at: string
        }
        Insert: {
          user_id: string
          balance?: number
          updated_at?: string
        }
        Update: {
          user_id?: string
          balance?: number
          updated_at?: string
        }
      }
      usage_logs: {
        Row: {
          id: string
          user_id: string
          api_key_id: string | null
          endpoint: string
          tokens_consumed: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          api_key_id?: string | null
          endpoint: string
          tokens_consumed: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          api_key_id?: string | null
          endpoint?: string
          tokens_consumed?: number
          created_at?: string
        }
      }
      renders: {
        Row: {
          id: string
          user_id: string
          job_id: string
          status: string
          shotstack_url: string | null
          gcs_url: string | null
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          job_id: string
          status?: string
          shotstack_url?: string | null
          gcs_url?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          job_id?: string
          status?: string
          shotstack_url?: string | null
          gcs_url?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
      }
      stripe_customers: {
        Row: {
          user_id: string
          stripe_customer_id: string
          created_at: string
        }
        Insert: {
          user_id: string
          stripe_customer_id: string
          created_at?: string
        }
        Update: {
          user_id?: string
          stripe_customer_id?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}